### ISSUE TITLE
There is a bug

### ISSUE THREAD

**Issue by baiyunping333** [chitamoor/Rester#12]
in testcase.py:27, 
```
for test in test_suite.test_cases:
    self.run_test_case(test)
```
*test* is a TestCase instance, not a file path string.
maybe right is:
```
for test in test_suite.test_cases:
    if isinstance(test, str):
        self.run_test_case(test)
    elif isinstance(test, TestCase):
        test.load()
        self._run_case(test)
    else:
        self.logger.info("not valid test case")
```

**Comment by rizwan582** [comment]
yes I've faced this bug as well. The way I've fixed is by updating line 30 of testcase.py file as follows:

original line:
```python
case = TestCase(None, test_case_file_name)        
```
fixed line:
```python
case = TestCase(None, test_case_file_name.filename) # test_case_file_name.filename instead of test_case_file_name
```


May have other better fix, but at least this is working for me for the time being.

**Comment by chitamoor** [comment]
Thanks for the suggestions and workarounds. Checked in a commit to fix the issue reported.
